# Generated by Django 5.0.2 on 2024-02-13 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App1", "0002_profesion_alter_frasedb_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autordb",
            name="profesion",
            field=models.ManyToManyField(
                related_name="autores", to="App1.profesion", verbose_name="Profesion"
            ),
        ),
        migrations.AlterField(
            model_name="frasedb",
            name="autor_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="frases",
                to="App1.autordb",
            ),
        ),
    ]
